export const tablica = [
    {
      StandingsID: 1,
      TeamID: 1,
      SeasonID: 1,
      Rank: 1,
      Wins: 12,
      Draws: 4,
      Losses: 2,
      GoalsScored: 40,
      GoalsConceded: 20,
      Points: 40,
    },
    {
      StandingsID: 2,
      TeamID: 2,
      SeasonID: 1,
      Rank: 2,
      Wins: 10,
      Draws: 6,
      Losses: 2,
      GoalsScored: 35,
      GoalsConceded: 18,
      Points: 36,
    },
    {
      StandingsID: 3,
      TeamID: 3,
      SeasonID: 1,
      Rank: 3,
      Wins: 9,
      Draws: 4,
      Losses: 5,
      GoalsScored: 30,
      GoalsConceded: 25,
      Points: 31,
    },
    {
      StandingsID: 4,
      TeamID: 4,
      SeasonID: 1,
      Rank: 4,
      Wins: 8,
      Draws: 5,
      Losses: 5,
      GoalsScored: 28,
      GoalsConceded: 20,
      Points: 29,
    },
    {
      StandingsID: 5,
      TeamID: 5,
      SeasonID: 1,
      Rank: 5,
      Wins: 7,
      Draws: 6,
      Losses: 5,
      GoalsScored: 25,
      GoalsConceded: 22,
      Points: 27,
    },
  ]