[[redirects]]
  from = "/api/*"
  to = "https://www.umadomena.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/app.js"  # Adjust this line to match your entry point
  status = 200